Repository locospec/lens, pull requests merged in 2025-01, with the labels that each got.

#1 Table sample
  configs/README.md
  configs/package.json
  package-lock.json
  package.json
  packages/elements-react/lib/components/Checkbox/index.tsx
  packages/elements-react/lib/components/table/List.tsx
  packages/elements-react/lib/components/table/ListData.tsx
  packages/elements-react/lib/components/table/ResizeHandle.tsx
  packages/elements-react/lib/components/table/TableBody.tsx
  packages/elements-react/lib/components/table/TableCell.tsx
  packages/elements-react/lib/components/table/TableHeader.tsx
  packages/elements-react/lib/components/table/TableHeaderSection.tsx
  packages/elements-react/lib/components/table/TableMetrics.tsx
  packages/elements-react/lib/components/table/TableRow.tsx
  packages/elements-react/lib/components/table/css/divTable.css
  packages/elements-react/lib/components/table/hooks/useTableConfig.tsx
  packages/elements-react/lib/components/table/index.tsx
  packages/elements-react/lib/components/table/table.tsx
  packages/elements-react/lib/components/utils/cn.ts
  packages/elements-react/lib/main.ts
  packages/elements-react/package.json
Labels: prerelease

#2 fix: fixed issue with peer dep in elements
  package-lock.json
Labels: prerelease

#3 chore: Added commment
  packages/elements-react/lib/components/table/TableBody.tsx
Labels: prerelease

#4 Table sample
  .github/workflows/release.yml
  packages/elements-react/README.md
  packages/elements-react/lib/components/Button/index.tsx
  packages/elements-react/package.json
Labels: prerelease

#6 chore: modified button component
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#7 Table sample
  .github/workflows/site-deploy.yml
  .github/workflows/site-preview.yml
  README.md
  apps/site/.gitignore
  apps/site/README.md
  apps/site/blog/2019-05-28-first-blog-post.md
  apps/site/blog/2019-05-29-long-blog-post.md
  apps/site/blog/2021-08-01-mdx-blog-post.mdx
  apps/site/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  apps/site/blog/2021-08-26-welcome/index.md
  apps/site/blog/authors.yml
  apps/site/blog/tags.yml
  apps/site/docs/intro.md
  apps/site/docs/tutorial-basics/_category_.json
  apps/site/docs/tutorial-basics/congratulations.md
  apps/site/docs/tutorial-basics/create-a-blog-post.md
  apps/site/docs/tutorial-basics/create-a-document.md
  apps/site/docs/tutorial-basics/create-a-page.md
  apps/site/docs/tutorial-basics/deploy-your-site.md
  apps/site/docs/tutorial-basics/markdown-features.mdx
  apps/site/docs/tutorial-extras/_category_.json
  apps/site/docs/tutorial-extras/img/docsVersionDropdown.png
  apps/site/docs/tutorial-extras/img/localeDropdown.png
  apps/site/docs/tutorial-extras/manage-docs-versions.md
  apps/site/docs/tutorial-extras/translate-your-site.md
  apps/site/docusaurus.config.ts
  apps/site/package.json
  apps/site/sidebars.ts
  apps/site/src/components/HomepageFeatures/index.tsx
  apps/site/src/components/HomepageFeatures/styles.module.css
  apps/site/src/css/custom.css
  apps/site/src/pages/index.module.css
  apps/site/src/pages/index.tsx
  apps/site/src/pages/markdown-page.md
  apps/site/static/.nojekyll
  apps/site/static/img/docusaurus-social-card.jpg
  apps/site/static/img/docusaurus.png
  apps/site/static/img/favicon.ico
  apps/site/static/img/logo.svg
  apps/site/static/img/undraw_docusaurus_mountain.svg
  apps/site/static/img/undraw_docusaurus_react.svg
  apps/site/static/img/undraw_docusaurus_tree.svg
  apps/site/tsconfig.json
  lerna.json
  package-lock.json
  package.json
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#10 Table sample
  .github/workflows/site-deploy.yml
  .github/workflows/site-preview.yml
  CNAME
  README.md
  apps/site/.ladle/components.tsx
  apps/site/.ladle/config.mjs
  apps/site/.ladle/styles.css
  apps/site/blog/2019-05-28-first-blog-post.md
  apps/site/blog/2021-08-01-mdx-blog-post.mdx
  apps/site/docusaurus.config.ts
  apps/site/package.json
  apps/site/plugins/docusaurus-tailwindcss-loader/index.js
  apps/site/postcss.config.js
  apps/site/src/components/ResizableLadlePreview.tsx
  apps/site/src/css/custom.css
  apps/site/src/pages/tailwind.tsx
  apps/site/src/stories/page.stories.tsx
  apps/site/src/styles/alignment.css
  apps/site/src/styles/avatar.css
  apps/site/src/styles/blog.css
  apps/site/src/styles/docs-page.css
  apps/site/src/styles/docs-sidebar.css
  apps/site/src/styles/font-sizes.css
  apps/site/src/styles/hero.css
  apps/site/src/styles/root-styles.css
  apps/site/src/styles/tailwind.css
  apps/site/tailwind.config.ts
  package-lock.json
  package.json
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#11 chore: modified button log
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#12 chore: added optional dep
  package-lock.json
  package.json
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#13 Table sample
  .github/workflows/release.yml
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#15 Table sample
  .github/workflows/site-deploy.yml
  .github/workflows/site-preview.yml
  README.md
  apps/site/.ladle/components.tsx
  apps/site/.ladle/config.mjs
  apps/site/.ladle/styles.css
  apps/site/blog/2021-08-01-mdx-blog-post.mdx
  apps/site/package.json
  apps/site/src/components/ResizablePreview.tsx
  apps/site/src/pages/tailwind.tsx
  apps/site/src/pages/tailwind_2.tsx
  package-lock.json
  package.json
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#17 ci: modified build command
  package.json
Labels: prerelease

#18 doc: changed log for button message
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#19 Blueprint_init
  .github/workflows/site-deploy.yml
  .github/workflows/site-preview.yml
  apps/site/package.json
  apps/site/src/pages/tailwind.tsx
  apps/site/tailwind.config.ts
  lerna.json
  package-lock.json
  package.json
  packages/blueprint-react/.eslintrc.cjs
  packages/blueprint-react/.gitignore
  packages/blueprint-react/.nvmrc
  packages/blueprint-react/README.md
  packages/blueprint-react/index.html
  packages/blueprint-react/lib/components/Button/index.tsx
  packages/blueprint-react/lib/components/Button/styles.module.css
  packages/blueprint-react/lib/components/Field/index.tsx
  packages/blueprint-react/lib/components/Input/index.tsx
  packages/blueprint-react/lib/components/Label/index.tsx
  packages/blueprint-react/lib/components/Label/styles.module.css
  packages/blueprint-react/lib/main.ts
  packages/blueprint-react/lib/vite-env.d.ts
  packages/blueprint-react/package.json
  packages/blueprint-react/public/vite.svg
  packages/blueprint-react/src/App.css
  packages/blueprint-react/src/App.tsx
  packages/blueprint-react/src/assets/react.svg
  packages/blueprint-react/src/index.css
  packages/blueprint-react/src/main.tsx
  packages/blueprint-react/src/tailwind-entry.css
  packages/blueprint-react/src/vite-env.d.ts
  packages/blueprint-react/tailwind.config.js
  packages/blueprint-react/tsconfig.app.json
  packages/blueprint-react/tsconfig.json
  packages/blueprint-react/tsconfig.lib.json
  packages/blueprint-react/tsconfig.node.json
  packages/blueprint-react/vite.config.ts
Labels: prerelease

#22 Blueprint_init
  packages/blueprint-react/README.md
Labels: prerelease

#25 feat: Added msg log in button
  package.json
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#26 test: Added log in button
  package.json
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#27 Table sample
  .github/workflows/release.yml
  package.json
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#28 feat: Modified script with log msg
  .github/workflows/release.yml
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#29 Table sample
  .github/workflows/release.yml
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#30 Blueprint_init
  .github/workflows/bp-react-release.yml
Labels: prerelease

#32 Table sample
  apps/site/package.json
  packages/elements-react/lib/components/Button/index.tsx
  packages/elements-react/vite.config.ts
Labels: prerelease

#33 doc: sample
  .github/workflows/release.yml
  packages/elements-react/lib/components/Button/index.tsx
Labels: prerelease

#34 fix: correct exclamation marks in Label component header
  package.json
  packages/blueprint-react/lib/components/Label/index.tsx
Labels: patch, release

#35 Sample
  package-lock.json
  packages/elements-react/lib/components/Button/index.tsx
Labels: patch, release

#36 feat: smaple
  .github/workflows/release.yml
  packages/elements-react/lib/components/Button/index.tsx
Labels: patch, release

#37 chore: Added sample log
  packages/blueprint-react/lib/components/Button/index.tsx
Labels: patch, release

#38 Blueprint m changes
  .github/workflows/bp-react-release.yml
  packages/blueprint-react/lib/components/Label/index.tsx
Labels: patch, release

#39 Blueprint m changes
  apps/site/package.json
  lerna.json
  package-lock.json
  package.json
  packages/blueprint-react/lib/components/Label/index.tsx
Labels: patch, release

#40 fix: Update npm plugin configuration in package.json
  package.json
Labels: patch, release

#41 fix: Remove extra punctuation from header in Label component
  packages/blueprint-react/lib/components/Label/index.tsx
Labels: patch, release

#42 Blueprint m changes
  package.json
  packages/blueprint-react/lib/components/Label/index.tsx
Labels: patch

#43 fix: Remove extra punctuation from header in Label component
  packages/blueprint-react/lib/components/Label/index.tsx
Labels: patch, release

#44 fix: Update header punctuation in Label component
  packages/blueprint-react/lib/components/Label/index.tsx
Labels: patch, release

#45 fix: Correct greeting text in Label component
  packages/blueprint-react/lib/components/Label/index.tsx
Labels: patch, release

#46 fix: Update greeting text in Label component for consistency
  packages/blueprint-react/lib/components/Label/index.tsx
Labels: release

#47 Blueprint_alpha_changes
  packages/blueprint-react/lib/components/Label/index.tsx
Labels: release

#48 Alpha
  .github/workflows/release.yml
  packages/blueprint-react/lib/components/Label/index.tsx
  packages/elements-react/vite.config.ts
Labels: release

#54 fix: Added fix type commit for testing auto workflow
  packages/elements-react/lib/components/Button/index.tsx
Labels: patch

#55 Auto testing
  package-lock.json
  package.json
  packages/elements-react/lib/components/Button/index.tsx
Labels: patch

#56 Auto testing
  package-lock.json
  packages/elements-react/lib/components/Button/index.tsx
  packages/elements-react/package.json
Labels: patch

#57 Auto testing
  .github/workflows/release.yml
  packages/elements-react/lib/components/Button/index.tsx
Labels: patch

#58 Auto testing
  .github/workflows/release.yml
  package.json
  packages/elements-react/lib/components/Button/index.tsx
Labels: patch

#59 Auto testing
  package.json
  packages/elements-react/lib/components/Button/index.tsx
Labels: patch, release

#60 patch: Added console.log for button
  packages/elements-react/lib/components/Button/index.tsx
Labels: patch, release

#62 Testing single commit with start of `fix` type
  packages/elements-react/lib/components/Checkbox/index.tsx
Labels: release

#63 Testing auto commits based on commit type
  packages/elements-react/lib/components/Checkbox/index.tsx
Labels: release

#64 Auto testing
  packages/elements-react/lib/components/Button/index.tsx
  packages/elements-react/lib/components/Checkbox/index.tsx
Labels: release

#65 Auto testing
  packages/elements-react/lib/components/Button/index.tsx
  packages/elements-react/lib/components/Checkbox/index.tsx
  packages/elements-react/lib/components/Field/index.tsx
Labels: patch, release

#66 patch: modified console.log in button
  packages/elements-react/lib/components/Button/index.tsx
Labels: minor, release

#67 Testing PR merge without release tag
  packages/elements-react/lib/components/Button/index.tsx
Labels: patch

#68 Testing without release label after adding a feat type commit
  packages/elements-react/lib/components/Button/index.tsx
Labels: patch

#69 Auto testing
  packages/elements-react/lib/components/Button/index.tsx
  packages/elements-react/lib/components/Checkbox/index.tsx
  packages/elements-react/lib/components/Field/index.tsx
Labels: patch, release

#71 Auto testing for version
  packages/elements-react/lib/components/Button/index.tsx
  packages/elements-react/lib/components/Checkbox/index.tsx
  packages/elements-react/lib/components/Field/index.tsx
Labels: release

#74 AutoTesting: modified log in button
  packages/elements-react/lib/components/Button/index.tsx
Labels: release

#77 Auto testing
  packages/elements-react/lib/components/Field/index.tsx
Labels: release

#53 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: skip-release

#84 patch: modified log in button
  packages/elements-react/lib/components/Button/index.tsx
Labels: release

#92 fix(lens): add type interface for TableHeaderSection
  packages/elements-react/lib/components/table/TableHeaderSection.tsx
Labels: release

#96 patch(lens): modified table header
  packages/elements-react/lib/components/table/TableHeader.tsx
Labels: release

#98 Lens initial
  package-lock.json
  package.json
  packages/elements-react/index.css
  packages/elements-react/lib/components/Checkbox/index.tsx
  packages/elements-react/lib/components/table/Lens.tsx
  packages/elements-react/lib/components/table/ListData.tsx
  packages/elements-react/lib/components/table/ResizeHandle.tsx
  packages/elements-react/lib/components/table/TableBody.tsx
  packages/elements-react/lib/components/table/TableCell.tsx
  packages/elements-react/lib/components/table/TableHeader.tsx
  packages/elements-react/lib/components/table/TableHeaderSection.tsx
  packages/elements-react/lib/components/table/TableMetrics.tsx
  packages/elements-react/lib/components/table/TableRow.tsx
  packages/elements-react/lib/components/table/css/divTable.css
  packages/elements-react/lib/components/table/hooks/useTableConfig.tsx
  packages/elements-react/lib/main.ts
  packages/elements-react/package.json
  packages/elements-react/postcss.config.js
  packages/elements-react/src/App.css
  packages/elements-react/src/App.tsx
  packages/elements-react/src/index.css
  packages/elements-react/src/main.tsx
  packages/elements-react/src/mocks/mirageServer.ts
  packages/elements-react/src/tailwind-entry.css
  packages/elements-react/tailwind.config.js
  packages/elements-react/tailwind.config.ts
  packages/elements-react/tsconfig.app.json
  packages/elements-react/tsconfig.lib.json
Labels: release

#99 Release test
  packages/elements-react/package.json
  packages/elements-react/src/App.tsx
Labels: release

#100 patch: Add heading to lens sample in elements-react app
  packages/elements-react/src/App.tsx
Labels: release
